source "https://rubygems.org"

gem "jekyll", "~> 3.0"
gem "minimal-mistakes-jekyll"
gem "kramdown-parser-gfm"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "octopress"

gem 'wdm', '>= 0.1.0' if Gem.win_platform?
